
x-db-creds: &db-env
  MIKRO_ORM_HOST: database
  MIKRO_ORM_PORT: 3306
  MIKRO_ORM_USER: root
  MIKRO_ORM_PASSWORD: ""
  MIKRO_ORM_DB_NAME: techtest

services:
  database:
    image: mysql:8.0.32
    container_name: database
    working_dir: /project
    environment:
      MYSQL_DATABASE: techtest
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3310:3306'
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1073741824
    restart: always
    networks:
      - docker_network

networks:
  docker_network:
